# Generated by Django 3.1.3 on 2020-11-27 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=64, verbose_name='菜单名称')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('menu_type', models.IntegerField(choices=[(0, '菜单'), (1, '按钮')], verbose_name='菜单类型')),
                ('menu_icon', models.CharField(max_length=128, verbose_name='记录icon名称')),
                ('menu_order_num', models.IntegerField(unique=True, verbose_name='排序字段')),
                ('menu_url', models.CharField(max_length=256, verbose_name='路由名称')),
                ('parent_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system_manager.menu')),
            ],
        ),
    ]
