# Generated by Django 3.1.3 on 2020-11-27 03:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_name', models.CharField(max_length=64, verbose_name='部门名称')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('order_num', models.IntegerField(null=True, verbose_name='排序字段')),
                ('parent_dep', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_center.department')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.IntegerField(choices=[(0, '管理员'), (1, '测试'), (2, '普通用户')], verbose_name='用户角色')),
                ('role_desc', models.CharField(max_length=256, null=True, verbose_name='角色描述')),
                ('create_time', models.DateTimeField(default=datetime.datetime(2020, 11, 27, 11, 20, 16, 587441), verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=128, verbose_name='用户名称')),
                ('email', models.CharField(max_length=64, null=True, verbose_name='用户邮箱')),
                ('gender', models.SmallIntegerField(choices=[(0, '男性'), (1, '女性')], null=True, verbose_name='性别')),
                ('create_time', models.DateTimeField(db_index=True, default=datetime.datetime(2020, 11, 27, 11, 20, 16, 587441), verbose_name='创建时间')),
                ('last_login_time', models.DateTimeField(db_index=True, default=datetime.datetime(2020, 11, 27, 11, 20, 16, 587441), verbose_name='最后登录时间')),
                ('personal_desc', models.CharField(max_length=256, null=True, verbose_name='个人描述')),
                ('phone_number', models.CharField(max_length=32, null=True, verbose_name='电话号码')),
                ('use_status', models.SmallIntegerField(choices=[(0, '不可用'), (1, '可用')], null=True, verbose_name='用户状态')),
                ('last_update_time', models.DateTimeField(db_index=True, default=datetime.datetime(2020, 11, 27, 11, 20, 16, 587441), verbose_name='修改时间')),
                ('avatar', models.CharField(max_length=512, null=True, verbose_name='图片地址')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_center.department')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_center.role')),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_name', models.CharField(max_length=128, verbose_name='权限名称')),
                ('router_url', models.CharField(max_length=128, null=True, verbose_name='路由地址')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('parent_permission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_center.permission', verbose_name='父级权限')),
                ('role', models.ManyToManyField(to='user_center.Role')),
            ],
        ),
    ]
