# Generated by Django 3.1.3 on 2020-11-27 03:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_center', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=128, verbose_name='用户密码'),
        ),
        migrations.AlterField(
            model_name='role',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 27, 11, 24, 28, 327215), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='create_time',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 11, 27, 11, 24, 28, 328240), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login_time',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 11, 27, 11, 24, 28, 328240), verbose_name='最后登录时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_update_time',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 11, 27, 11, 24, 28, 328240), verbose_name='修改时间'),
        ),
    ]
