# Generated by Django 3.1.3 on 2020-11-27 06:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user_center', '0003_auto_20201127_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 27, 14, 46, 52, 290615), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='create_time',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 11, 27, 6, 46, 52, 291641, tzinfo=utc), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login_time',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 11, 27, 14, 46, 52, 291641), verbose_name='最后登录时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_update_time',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 11, 27, 14, 46, 52, 291641), verbose_name='修改时间'),
        ),
    ]
