# Generated by Django 3.1.3 on 2020-11-27 06:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_center', '0004_auto_20201127_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='create_time',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login_time',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='最后登录时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_update_time',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='修改时间'),
        ),
    ]
